# Generated by Django 4.2.2 on 2023-06-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icecream',
            options={'ordering': ('name',), 'verbose_name': 'мороженое', 'verbose_name_plural': 'мороженое'},
        ),
    ]
