# Generated by Django 4.2.2 on 2023-06-28 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0005_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icecream',
            name='image',
        ),
    ]
