# Generated by Django 4.2.2 on 2023-07-08 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_delete_icecreamcategory'),
        ('ice_cream', '0006_remove_icecream_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='IceCreamCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ice_cream.icecream')),
            ],
        ),
        migrations.AddField(
            model_name='icecream',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='ice_cream', through='ice_cream.IceCreamCategory', to='catalog.category', verbose_name='Категории'),
        ),
    ]
