# Generated by Django 4.2.2 on 2023-07-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0007_icecreamcategory_icecream_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icecream',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icecream',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
