# Generated by Django 4.2.2 on 2023-07-08 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_image_icecreamcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IceCreamCategory',
        ),
    ]
