# Generated by Django 4.2.2 on 2023-07-16 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0008_icecream_meta_description_icecream_meta_keywords_and_more'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderIceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ice_cream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ice_cream.icecream')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ice_cream', to='order.order')),
            ],
        ),
    ]
