# Generated by Django 4.2.2 on 2023-07-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_ordericecream'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('in_progress', 'В обробці'), ('waiting_for_payment', 'Очікується оплата'), ('in_delivery', 'Відправлено'), ('completed', 'Завершено'), ('canceled', 'Скасовано')], default='in_progress', max_length=100, null=True, verbose_name='Статус'),
        ),
    ]
